_format_version: "2.1"
_transform: true

services:
  - name: example-service
    url: http://172.28.0.4:4000/test
    routes:
      - name: jspath
        paths:
        - /test
    plugins:
      - name: keycloak-plugin

